/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"


#include "Driver_Adc.h"
#include "Driver_Stm.h"
#include "GTM_TOM_PWM.h"
#include "FNDSPI.h"
#include "DHT11.h"

#include "Driver_DHT11.h"

#include "Bsp.h"

#define DHT11_UPDATE_TIME                   500000000

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

void initGPIO();

uint8 temp;
uint8_t hum = 0;
volatile int cnt = 0;
void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    initFND();
    initGPIO();
    Driver_Stm_Init();
//    DHT11_init_comm();
    while(1)
    {
//        setFNDNumber(temp);
        setFNDNumber(hum);
        AppScheduling();
    }
}

void initGPIO(){
    IfxPort_setPinModeOutput(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex,IfxPort_OutputMode_pushPull,IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex,IfxPort_OutputMode_pushPull,IfxPort_OutputIdx_general);
    IfxPort_setPinLow(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
    IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
}

void AppScheduling(void){
    if(stSchedulingInfo.u8nuScheduling1msFlag){
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();
        if(stSchedulingInfo.u8nuScheduling10msFlag){
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();

            if(stSchedulingInfo.u8nuScheduling100msFlag){
                stSchedulingInfo.u8nuScheduling100msFlag = 0u;
                AppTask100ms();

                if(stSchedulingInfo.u8nuScheduling1000msFlag){
                    stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
                    AppTask1000ms();
                }
            }
        }
    }
}

void AppTask1ms(){ }
void AppTask10ms(){
}
void AppTask100ms(){

}
int task1000msCount = 0;
void AppTask1000ms(){
    task1000msCount = (task1000msCount + 1) % 1000;
//    DHT11_read_sensor();
//    if(g_dht11_one_eye_data.data_valid){
//        temp = g_dht11_one_eye_data.humidity;
//    }
    if(task1000msCount % 3 == 0){
        DHT11_Start();
        if(DHT11_Check_Response()){
            hum = DHT11_Read();
            DHT11_Read();
            DHT11_Read();
            DHT11_Read();
            DHT11_Read();
        }
    }
}

